from collections.abc import Sequence
import enum
from typing import Annotated, overload

from numpy.typing import ArrayLike

from . import (
    baxter as baxter,
    fetch as fetch,
    panda as panda,
    sphere as sphere,
    ur5 as ur5
)


class RRTCSettings:
    def __init__(self) -> None: ...

    @property
    def range(self) -> float: ...

    @range.setter
    def range(self, arg: float, /) -> None: ...

    @property
    def dynamic_domain(self) -> bool: ...

    @dynamic_domain.setter
    def dynamic_domain(self, arg: bool, /) -> None: ...

    @property
    def radius(self) -> float: ...

    @radius.setter
    def radius(self, arg: float, /) -> None: ...

    @property
    def alpha(self) -> float: ...

    @alpha.setter
    def alpha(self, arg: float, /) -> None: ...

    @property
    def min_radius(self) -> float: ...

    @min_radius.setter
    def min_radius(self, arg: float, /) -> None: ...

    @property
    def balance(self) -> bool: ...

    @balance.setter
    def balance(self, arg: bool, /) -> None: ...

    @property
    def tree_ratio(self) -> float: ...

    @tree_ratio.setter
    def tree_ratio(self, arg: float, /) -> None: ...

    @property
    def max_iterations(self) -> int: ...

    @max_iterations.setter
    def max_iterations(self, arg: int, /) -> None: ...

    @property
    def max_samples(self) -> int: ...

    @max_samples.setter
    def max_samples(self, arg: int, /) -> None: ...

    @property
    def start_tree_first(self) -> bool: ...

    @start_tree_first.setter
    def start_tree_first(self, arg: bool, /) -> None: ...

class AORRTCSettings:
    def __init__(self) -> None: ...

    @property
    def rrtc(self) -> RRTCSettings: ...

    @rrtc.setter
    def rrtc(self, arg: RRTCSettings, /) -> None: ...

    @property
    def simplify(self) -> SimplifySettings: ...

    @simplify.setter
    def simplify(self, arg: SimplifySettings, /) -> None: ...

    @property
    def optimize(self) -> bool: ...

    @optimize.setter
    def optimize(self, arg: bool, /) -> None: ...

    @property
    def cost_bound_resample(self) -> bool: ...

    @cost_bound_resample.setter
    def cost_bound_resample(self, arg: bool, /) -> None: ...

    @property
    def simplify_intermediate(self) -> bool: ...

    @simplify_intermediate.setter
    def simplify_intermediate(self, arg: bool, /) -> None: ...

    @property
    def use_phs(self) -> bool: ...

    @use_phs.setter
    def use_phs(self, arg: bool, /) -> None: ...

    @property
    def anytime(self) -> bool: ...

    @anytime.setter
    def anytime(self, arg: bool, /) -> None: ...

    @property
    def max_iterations(self) -> int: ...

    @max_iterations.setter
    def max_iterations(self, arg: int, /) -> None: ...

    @property
    def max_internal_iterations(self) -> int: ...

    @max_internal_iterations.setter
    def max_internal_iterations(self, arg: int, /) -> None: ...

    @property
    def max_cost_bound_resamples(self) -> int: ...

    @max_cost_bound_resamples.setter
    def max_cost_bound_resamples(self, arg: int, /) -> None: ...

    @property
    def max_samples(self) -> int: ...

    @max_samples.setter
    def max_samples(self, arg: int, /) -> None: ...

class PRMNeighborParams:
    def __init__(self, arg0: int, arg1: float, /) -> None: ...

    @property
    def dim(self) -> int: ...

    @dim.setter
    def dim(self, arg: int, /) -> None: ...

    @property
    def space_measure(self) -> float: ...

    @space_measure.setter
    def space_measure(self, arg: float, /) -> None: ...

    @property
    def gamma_scale(self) -> float: ...

    @gamma_scale.setter
    def gamma_scale(self, arg: float, /) -> None: ...

    def max_neighbors(self, arg: int, /) -> int: ...

    def neighbor_radius(self, arg: int, /) -> float: ...

class PRMSettings:
    def __init__(self, arg: PRMNeighborParams, /) -> None: ...

    @property
    def max_iterations(self) -> int: ...

    @max_iterations.setter
    def max_iterations(self, arg: int, /) -> None: ...

    @property
    def max_samples(self) -> int: ...

    @max_samples.setter
    def max_samples(self, arg: int, /) -> None: ...

    @property
    def neighbor_params(self) -> PRMNeighborParams: ...

    @neighbor_params.setter
    def neighbor_params(self, arg: PRMNeighborParams, /) -> None: ...

    def max_neighbors(self, arg: int, /) -> int: ...

    def neighbor_radius(self, arg: int, /) -> float: ...

class FCITNeighborParams:
    def __init__(self, arg0: int, arg1: float, /) -> None: ...

    @property
    def dim(self) -> int: ...

    @dim.setter
    def dim(self, arg: int, /) -> None: ...

    @property
    def space_measure(self) -> float: ...

    @space_measure.setter
    def space_measure(self, arg: float, /) -> None: ...

    @property
    def gamma_scale(self) -> float: ...

    @gamma_scale.setter
    def gamma_scale(self, arg: float, /) -> None: ...

    def max_neighbors(self, arg: int, /) -> int: ...

    def neighbor_radius(self, arg: int, /) -> float: ...

class FCITSettings:
    def __init__(self, arg: FCITNeighborParams, /) -> None: ...

    @property
    def max_iterations(self) -> int: ...

    @max_iterations.setter
    def max_iterations(self, arg: int, /) -> None: ...

    @property
    def max_samples(self) -> int: ...

    @max_samples.setter
    def max_samples(self, arg: int, /) -> None: ...

    @property
    def batch_size(self) -> int: ...

    @batch_size.setter
    def batch_size(self, arg: int, /) -> None: ...

    @property
    def optimize(self) -> bool: ...

    @optimize.setter
    def optimize(self, arg: bool, /) -> None: ...

    @property
    def neighbor_params(self) -> FCITNeighborParams: ...

    @neighbor_params.setter
    def neighbor_params(self, arg: FCITNeighborParams, /) -> None: ...

    def max_neighbors(self, arg: int, /) -> int: ...

    def neighbor_radius(self, arg: int, /) -> float: ...

class SimplifyRoutine(enum.Enum):
    BSPLINE = 0

    REDUCE = 1

    SHORTCUT = 2

    PERTURB = 3

BSPLINE: SimplifyRoutine = SimplifyRoutine.BSPLINE

REDUCE: SimplifyRoutine = SimplifyRoutine.REDUCE

SHORTCUT: SimplifyRoutine = SimplifyRoutine.SHORTCUT

PERTURB: SimplifyRoutine = SimplifyRoutine.PERTURB

class BSplineSettings:
    def __init__(self) -> None: ...

    @property
    def max_steps(self) -> int: ...

    @max_steps.setter
    def max_steps(self, arg: int, /) -> None: ...

    @property
    def min_change(self) -> float: ...

    @min_change.setter
    def min_change(self, arg: float, /) -> None: ...

    @property
    def midpoint_interpolation(self) -> float: ...

    @midpoint_interpolation.setter
    def midpoint_interpolation(self, arg: float, /) -> None: ...

class ReduceSettings:
    def __init__(self) -> None: ...

    @property
    def max_steps(self) -> int: ...

    @max_steps.setter
    def max_steps(self, arg: int, /) -> None: ...

    @property
    def max_empty_steps(self) -> int: ...

    @max_empty_steps.setter
    def max_empty_steps(self, arg: int, /) -> None: ...

    @property
    def range_ratio(self) -> float: ...

    @range_ratio.setter
    def range_ratio(self, arg: float, /) -> None: ...

class ShortcutSettings:
    def __init__(self) -> None: ...

class PerturbSettings:
    def __init__(self) -> None: ...

    @property
    def max_steps(self) -> int: ...

    @max_steps.setter
    def max_steps(self, arg: int, /) -> None: ...

    @property
    def max_empty_steps(self) -> int: ...

    @max_empty_steps.setter
    def max_empty_steps(self, arg: int, /) -> None: ...

    @property
    def perturbation_attempts(self) -> int: ...

    @perturbation_attempts.setter
    def perturbation_attempts(self, arg: int, /) -> None: ...

    @property
    def range_ratio(self) -> float: ...

    @range_ratio.setter
    def range_ratio(self, arg: float, /) -> None: ...

class SimplifySettings:
    def __init__(self) -> None: ...

    @property
    def max_iterations(self) -> int: ...

    @max_iterations.setter
    def max_iterations(self, arg: int, /) -> None: ...

    @property
    def interpolate(self) -> int: ...

    @interpolate.setter
    def interpolate(self, arg: int, /) -> None: ...

    @property
    def operations(self) -> list[SimplifyRoutine]: ...

    @operations.setter
    def operations(self, arg: Sequence[SimplifyRoutine], /) -> None: ...

    @property
    def reduce(self) -> ReduceSettings: ...

    @reduce.setter
    def reduce(self, arg: ReduceSettings, /) -> None: ...

    @property
    def shortcut(self) -> ShortcutSettings: ...

    @shortcut.setter
    def shortcut(self, arg: ShortcutSettings, /) -> None: ...

    @property
    def perturb(self) -> PerturbSettings: ...

    @perturb.setter
    def perturb(self, arg: PerturbSettings, /) -> None: ...

    @property
    def bspline(self) -> BSplineSettings: ...

    @bspline.setter
    def bspline(self, arg: BSplineSettings, /) -> None: ...

class Sphere:
    def __init__(self, arg0: Sequence[float], arg1: float, /) -> None:
        """Constructor from center and radius."""

    @staticmethod
    def make_flat(arg0: float, arg1: float, arg2: float, arg3: float, /) -> Sphere: ...

    @staticmethod
    def make(arg0: Sequence[float], arg1: float, /) -> Sphere: ...

    @property
    def x(self) -> float: ...

    @property
    def y(self) -> float: ...

    @property
    def z(self) -> float: ...

    @property
    def r(self) -> float: ...

    @property
    def position(self) -> list[float]: ...

    @property
    def min_distance(self) -> float: ...

    @property
    def name(self) -> str: ...

    @name.setter
    def name(self, arg: str, /) -> None: ...

class Cylinder:
    @overload
    def __init__(self, arg0: Sequence[float], arg1: Sequence[float], arg2: float, arg3: float, /) -> None:
        """Constructor from center, Euler XYZ orientation, radius, and length."""

    @overload
    def __init__(self, arg0: Sequence[float], arg1: Sequence[float], arg2: float, /) -> None:
        """Constructor from endpoints and radius."""

    @property
    def x1(self) -> float: ...

    @property
    def y1(self) -> float: ...

    @property
    def z1(self) -> float: ...

    @property
    def x2(self) -> float: ...

    @property
    def y2(self) -> float: ...

    @property
    def z2(self) -> float: ...

    @property
    def xv(self) -> float: ...

    @property
    def yv(self) -> float: ...

    @property
    def zv(self) -> float: ...

    @property
    def r(self) -> float: ...

    @property
    def rdv(self) -> float: ...

    @property
    def min_distance(self) -> float: ...

    @property
    def name(self) -> str: ...

    @name.setter
    def name(self, arg: str, /) -> None: ...

class Cuboid:
    def __init__(self, arg0: Sequence[float], arg1: Sequence[float], arg2: Sequence[float], /) -> None:
        """Constructor from center, Euler XYZ orientation, and XYZ half-extents."""

    @property
    def x(self) -> float: ...

    @property
    def y(self) -> float: ...

    @property
    def z(self) -> float: ...

    @property
    def axis_1_x(self) -> float: ...

    @property
    def axis_1_y(self) -> float: ...

    @property
    def axis_1_z(self) -> float: ...

    @property
    def axis_2_x(self) -> float: ...

    @property
    def axis_2_y(self) -> float: ...

    @property
    def axis_2_z(self) -> float: ...

    @property
    def axis_3_x(self) -> float: ...

    @property
    def axis_3_y(self) -> float: ...

    @property
    def axis_3_z(self) -> float: ...

    @property
    def axis_1_r(self) -> float: ...

    @property
    def axis_2_r(self) -> float: ...

    @property
    def axis_3_r(self) -> float: ...

    @property
    def min_distance(self) -> float: ...

    @property
    def name(self) -> str: ...

    @name.setter
    def name(self, arg: str, /) -> None: ...

class Gaussian3:
    def __init__(self, mean: Sequence[float], sigma_upper: Sequence[float], alpha: float = 1.0) -> None:
        """
        Constructor: mean (xyz), covariance upper triangle (xx, xy, xz, yy, yz, zz), occupancy weight alpha.
        """

    @property
    def mx(self) -> float: ...

    @mx.setter
    def mx(self, arg: float, /) -> None: ...

    @property
    def my(self) -> float: ...

    @my.setter
    def my(self, arg: float, /) -> None: ...

    @property
    def mz(self) -> float: ...

    @mz.setter
    def mz(self, arg: float, /) -> None: ...

    @property
    def sigma_xx(self) -> float: ...

    @sigma_xx.setter
    def sigma_xx(self, arg: float, /) -> None: ...

    @property
    def sigma_xy(self) -> float: ...

    @sigma_xy.setter
    def sigma_xy(self, arg: float, /) -> None: ...

    @property
    def sigma_xz(self) -> float: ...

    @sigma_xz.setter
    def sigma_xz(self, arg: float, /) -> None: ...

    @property
    def sigma_yy(self) -> float: ...

    @sigma_yy.setter
    def sigma_yy(self, arg: float, /) -> None: ...

    @property
    def sigma_yz(self) -> float: ...

    @sigma_yz.setter
    def sigma_yz(self, arg: float, /) -> None: ...

    @property
    def sigma_zz(self) -> float: ...

    @sigma_zz.setter
    def sigma_zz(self, arg: float, /) -> None: ...

    @property
    def alpha(self) -> float: ...

    @alpha.setter
    def alpha(self, arg: float, /) -> None: ...

    @property
    def mean(self) -> list[float]: ...

    @property
    def sigma_upper(self) -> list[float]: ...

    def trace_sigma(self) -> float: ...

    def iso_sigma(self) -> float: ...

class GaussianObstacle(Gaussian3):
    def __init__(self, mean: Sequence[float], sigma_upper: Sequence[float], alpha: float = 1.0) -> None:
        """
        Constructor: mean (xyz), covariance upper triangle (xx, xy, xz, yy, yz, zz), occupancy weight alpha.
        """

    @property
    def three_sigma_extent(self) -> float: ...

    @property
    def min_distance(self) -> float: ...

    @property
    def name(self) -> str: ...

    @name.setter
    def name(self, arg: str, /) -> None: ...

def make_heightfield(arg0: Sequence[float], arg1: Sequence[float], arg2: Sequence[int], arg3: Sequence[float], /) -> HeightField: ...

class HeightField:
    @property
    def x(self) -> float: ...

    @property
    def y(self) -> float: ...

    @property
    def z(self) -> float: ...

    @property
    def xs(self) -> float: ...

    @property
    def ys(self) -> float: ...

    @property
    def zs(self) -> float: ...

    @property
    def data(self) -> list[float]: ...

class Environment:
    def __init__(self) -> None: ...

    def add_sphere(self, arg: Sphere, /) -> None: ...

    def add_cuboid(self, arg: Cuboid, /) -> None: ...

    def add_capsule(self, arg: Cylinder, /) -> None: ...

    def add_heightfield(self, arg: HeightField, /) -> None: ...

    def add_gaussian_obstacle(self, arg: GaussianObstacle, /) -> None: ...

    def add_pointcloud(self, arg0: Sequence[Sequence[float]], arg1: float, arg2: float, arg3: float, /) -> int: ...

    def attach(self, arg: Attachment, /) -> None: ...

    def detach(self) -> None: ...

    @property
    def spheres(self) -> list[Sphere]: ...

    @property
    def cuboids(self) -> list[Cuboid]: ...

    @property
    def z_aligned_cuboids(self) -> list[Cuboid]: ...

    @property
    def capsules(self) -> list[Cylinder]: ...

    @property
    def z_aligned_capsules(self) -> list[Cylinder]: ...

    @property
    def heightfields(self) -> list[HeightField]: ...

    @property
    def pointclouds(self) -> list["vamp::collision::CAPT"]: ...

    @property
    def gaussian_obstacles(self) -> list[GaussianObstacle]: ...

@overload
def filter_pointcloud(arg0: Sequence[Sequence[float]], arg1: float, arg2: float, arg3: Sequence[float], arg4: Sequence[float], arg5: Sequence[float], arg6: bool, /) -> tuple[list[list[float]], int]: ...

@overload
def filter_pointcloud(arg0: Annotated[ArrayLike, dict(dtype='float32', shape=(None, 3), device='cpu')], arg1: float, arg2: float, arg3: Sequence[float], arg4: Sequence[float], arg5: Sequence[float], arg6: bool, /) -> tuple[list[list[float]], int]: ...

def gaussian3_density(mean: Sequence[float], sigma_upper: Sequence[float]) -> float:
    """
    Evaluate N(mean; 0, sigma) for a 3D Gaussian with symmetric covariance given as upper-triangle row-major (xx, xy, xz, yy, yz, zz).
    """

def observation_reward(cx: float, cy: float, cz: float, nx: float, ny: float, nz: float, d_max: float, psi: float, gaussians: Sequence[Gaussian3]) -> float:
    """
    Camera-cone observation reward O(c, n_gaze) for a 3-D camera at world position (cx, cy, cz) looking along unit vector (nx, ny, nz). Per-kernel angular fraction is the non-central chi-squared (k=2) tail under the small-angle approximation (Marcum-Q form); radial fraction is the standard-normal CDF mass within d_max.  σ per kernel is sqrt(tr(Σ)/3).
    """

def optimal_gaze(cx: float, cy: float, cz: float, R_head: Sequence[float], n_ref: Sequence[float], d_max: float, psi: float, psi_h_az: float, psi_h_el: float, az_min: float, az_max: float, el_min: float, el_max: float, gaussians: Sequence[Gaussian3], n_grid: int = 9, n_refine: int = 20) -> tuple[float, float, float]:
    """
    Bounded 2-D search for the optimal (az*, el*) head-frame gaze offsets maximising the observation reward.  R_head is row-major 3×3; gaze = R_head · Rz(az) · Ry(el) · n_ref.  Search strategy: coarse n_grid×n_grid uniform scan over the window [-psi_h_*/2, +psi_h_*/2] ∩ [*_min, *_max], then per-axis golden-section refinement around the best cell (n_refine iterations each).  Returns (az*, el*, O*).
    """

def ncx2_2_cdf(z: float, lam: float) -> float:
    """
    P[χ²_2(λ) ≤ z] via Helstrom series (N=40 Poisson-mixture terms).  Used internally by observation_reward for the 3-D angular fraction.
    """

class Attachment:
    def __init__(self, arg: Annotated[ArrayLike, dict(dtype='float32', shape=(4, 4), order='F')], /) -> None:
        """
        Constructor for an attachment centered at a relative transform from the end-effector.
        """

    @property
    def relative_frame(self) -> "Eigen::Transform<float, 3, 1, 0>": ...

    def add_sphere(self, arg: Sphere, /) -> None: ...

    def add_spheres(self, arg: Sequence[Sphere], /) -> None: ...

    def set_ee_pose(self, tf: Annotated[ArrayLike, dict(dtype='float32', shape=(4, 4), order='F')]) -> None: ...

    @property
    def posed_spheres(self) -> list[Sphere]: ...

def robots() -> list[str]: ...
